### ISSUE TITLE
BB-BLACK x BB-BLACK WIFI

### ISSUE THREAD

**Issue by xalbornoz** [beagleboard/beaglebone-blue#15]
May I run a BB-BLACK REVc program on a BB-BLACK WIFI straightly ???

**Comment by jadonk** [comment]
This query doesn't belong here. Please post to https://beagleboard.org/discuss. 

Short answer, in most cases, yes, but you've said nothing about what your program would do. Will an ARM Linux program run on an ARM Linux board? In most cases, yes.

**Comment by xalbornoz** [comment]
Hi Jason.
Sorry for my wrong post ... And I thank yo so much for your short answer.
Regards,

Xavier

 
 

    On Tuesday, April 17, 2018, 12:03:21 AM GMT-3, Jason Kridner <notifications@github.com> wrote:  
 
 
This query doesn't belong here. Please post to https://beagleboard.org/discuss.

Short answer, in most cases, yes, but you've said nothing about what your program would do. Will an ARM Linux program run on an ARM Linux board? In most cases, yes.
