### ISSUE TITLE
beaglebone-blue with NodeMCU

### ISSUE THREAD

**Issue by kevin-armel** [beagleboard/beaglebone-blue#20]
Hello, I am an electronics enthusiast, I start with a beaglebone-blue . I would like to run two DC motors with a NodeMCU motor shield, but I can't connect my beaglebone to the shield. I can't find the right GPIO to connect the two.

**Comment by jadonk** [comment]
But, BeagleBone Blue has 4 motor drivers built in? Why do you want to use the NodeMCU motor shield?

Using the PWM outputs along with signals from the GPIO header would make it possible to use external drivers, but, again, why?

**Comment by FPSychotic** [comment]
Maybe are big motors

**Comment by kevin-armel** [comment]
thank's for your answers.
I finally finded solution by using BB Blue's PWM outputs
