### ISSUE TITLE
How to boot from MicroSD vs onboard memory - need instructions

### ISSUE THREAD

**Issue by dmalawey** [beagleboard/beaglebone-blue#23]
1) What exact steps tell my blue to boot from microSD?
2) What steps tell my blue to boot from onboard memory?
3) How can I query my blue on where it has booted from?
4) Can I tell by the LEDs where the blue is running it's OS?

**Comment by jadonk** [comment]
https://github.com/beagleboard/beaglebone-blue/wiki/Frequently-Asked-Questions-(FAQ)#Ive_written_the_latest_image_to_a_uSD_card_but_some_features_arent_working_How_do_I_make_it_run_properly

You cannot tell from the LEDs where the boot source is.

**Comment by dmalawey** [comment]
> For all issue reports, consider reading this document on smart questions.
I will do my best to implement these!
