### ISSUE TITLE
MPU9250 IMU temperature intended purpose?

### ISSUE THREAD

**Issue by dmalawey** [beagleboard/beaglebone-blue#25]
What is the intended purpose of temperature reading on the MPU9250?  Is it appropriate to measure ambient temperature or is it close to heat-generating components on the blue?

**Comment by jadonk** [comment]
From the datasheet:

> 4.19 Digital-Output Temperature Sensor
> An on-chip temperature sensor and ADC are used to measure the MPU-9250 die temperature. The readings
> from the ADC can be read from the FIFO or the Sensor Data registers.

I believe the primary purpose is compensation.

The MPU9250 and BMP280 are located in near proximity to each other. They are reasonably far from primary heat sources on the board, but there's certainly some impact. Using the combination is reasonable for getting the ambient temperature, but I would focus on the BMP280 temperature for compensating the pressure to determine altitude.

librobotcontrol will report altitude.
