### ISSUE TITLE
Looks like there are some errors

### ISSUE THREAD

**Issue by csann** [beagleboard/beaglebone-blue#4]
I'm definitely a newby but it looks like there are some errors on this spreadsheet. I would like to edit it, but only if someone would review my work. I am thinking about marking each cell I edited with a colored background to make it easy to see my changes. How should I submit my suggested changes?

**Comment by jadonk** [comment]
@csann look at github pull requests--that's the way. Can you point out specific issues?

**Comment by jadonk** [comment]
@csann No update in 6 months. Closing issue. Please re-open if you'd like to make suggested changes.
