### ISSUE TITLE
Thermal management

### ISSUE THREAD

**Issue by Russ76** [beagleboard/beaglebone-blue#6]
Should anything be done about thermal management for the CPU? I don't see this issue addressed anywhere in the BBBlue discussion.

**Comment by jadonk** [comment]
You need to keep it at a commercial temperature range (below 85C) to function. There is a thermal shutdown of sorts, but I wouldn't count on it. In general, there shouldn't be concerns if operating at room temperatures. If you need enclosed industrial or automotive environments, you'll want to think about a cooling system that'll keep the ambient temperature below 60C.
