### ISSUE TITLE
Motor driver chip is mislabelled

### ISSUE THREAD

**Issue by ElhemEnohpi** [beagleboard/beaglebone-blue#8]
BeagleBone_Blue_sch.pdf shows "TB6621FNG" but should be "TB6612FNG".

Don't feel bad though, you're not the only one!
https://github.com/sparkfun/Motor_Driver-Dual_TB6612FNG/issues/1

**Comment by jadonk** [comment]
@ElhemEnohpi actually, the misnaming was inherited from that one.
